<h1>Импорт библиотек

In [3]:
import numpy as np
import matplotlib.pyplot as plt

<h1>Задача 1. Дан набор из $p$ матриц размерностью $(n, n)$ и $p$ векторов размерностью $(n, 1)$, найти сумму произведений матриц на векторы. Написать тесты для кода

In [12]:
import numpy as np
import random

def sum_prod(X:np, V:np):
    result = np.zeros((n,1))

    for i in range(X.shape[1]):
        a=0
        for j in range(X.shape[0]):
            a+=X[i,j]*V[j,0]
        result[i,0]=a

    
    print(result)
    '''
    X - матрицы (n, n)
    V - векторы (n, 1)
    Гарантируется, что len(X) == len(V)
    '''

def mat_vet(p,n):
    for i in range(p):
        matr=np.random.randint(0,100,(n,n))
        vect=np.random.randint(0,100,(n,1))

        print("_______")
        print(matr)
        print(vect)
        sum_prod(matr,vect)
    pass

print("Пропишите кол-во матриц и векторов")    
p=int(input())
print("Укажите размерность")
n=int(input())

mat_vet(p,n)


Пропишите кол-во матриц и векторов
Укажите размерность
_______
[[89  1 11]
 [30 48 96]
 [49 80 93]]
[[46]
 [86]
 [82]]
[[ 5082.]
 [13380.]
 [16760.]]
_______
[[ 5 93 65]
 [55 95 74]
 [66 10 38]]
[[94]
 [31]
 [99]]
[[ 9788.]
 [15441.]
 [10276.]]


<h1>Задача 2. Дана матрица M, напишите функцию, которая бинаризует матрицу по некоторому threshold (то есть, все значения большие threshold становятся равными 1, иначе 0). Напишите тесты для кода

In [81]:
import numpy as np
import random

ss=int(input())
matrix=np.random.rand(ss,ss)

print(matrix)

(binarize(matrix))

def binarize(M:np, threshold=0.5):
    for i in range(M.shape[0]):
        for j in range(M.shape[1]):
            if (M[i,j]<threshold):
                M[i,j]=0
            else:
                M[i,j]=1

    print(M)

[[0.36170793 0.41820744 0.4326426  0.30283309 0.85053115]
 [0.2773275  0.795571   0.87459318 0.83794631 0.86870515]
 [0.68068357 0.07273948 0.73850264 0.68080638 0.64768551]
 [0.98222417 0.83657146 0.89802755 0.58557759 0.98785222]
 [0.13924199 0.89830546 0.87468471 0.58404327 0.00262615]]
[[0. 0. 0. 0. 1.]
 [0. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 0.]]


<h1>Задача 3. Напишите функцию, которая возвращает уникальные элементы из каждой строки матрицы. Напишите такую же функцию, но для столбцов. Напишите тесты для кода

In [ ]:
import numpy as np
import random

print("Введите размер однородной матрицы")

ss=int(input())
matr=np.random.randint(0,10, (ss,ss))


print(unique_rows(matr))
print(unique_columns(matr))


def unique_rows(mat:np):
    mas1=[]
    print(mat)
    for i in range(mat.shape[0]):
        mas1.append(np.unique(mat[i]))
    return mas1
        

def unique_columns(mat:np):
        mas2=[]
        for i in range(mat.shape[1]):
            mas2.append(np.unique(mat[:,i]))
        return mas2

Введите размер однородной матрицы
[[8 3 9 3 0]
 [2 0 4 5 0]
 [4 1 6 2 0]
 [9 2 8 8 7]
 [6 8 3 9 6]]
[array([0, 3, 8, 9], dtype=int32), array([0, 2, 4, 5], dtype=int32), array([0, 1, 2, 4, 6], dtype=int32), array([2, 7, 8, 9], dtype=int32), array([3, 6, 8, 9], dtype=int32)]
[array([2, 4, 6, 8, 9], dtype=int32), array([0, 1, 2, 3, 8], dtype=int32), array([3, 4, 6, 8, 9], dtype=int32), array([2, 3, 5, 8, 9], dtype=int32), array([0, 6, 7], dtype=int32)]


<h1>Задача 4. Напишите функцию, которая заполняет матрицу с размерами $(m, n)$ случайными числами, распределенными по нормальному закону. Затем считает мат. ожидание и дисперсию для каждого из столбцов и строк, а также строит для каждой строки и столбца гистограмму значений (использовать функцию hist из модуля matplotlib.plot)

In [ ]:
# Your code goes here

<h1>Задача 5. Напишите функцию, которая заполняет матрицу $(m, n)$ в шахматном порядке заданными числами $a$ и $b$. Напишите тесты для кода

In [56]:
import numpy as np

def chess(m, n, a, b):
    matrix=np.zeros((m,n))
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            if ((i+j)%2==0):
                matrix[i][j]=a
            else:
                matrix[i][j]=b
    print(matrix)

    pass


print("Введите кол-во строк матрицы")
m=int(input())
print("Введите кол-во столбцов матрицы")
n=int(input())
print("Введите первое число")
a=int(input())
print("Введите второе число")
b=int(input())

chess(m, n, a, b)

Введите кол-во строк матрицы
Введите кол-во столбцов матрицы
Введите первое число
Введите второе число
[[1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]]


<h1>Задача 6. Напишите функцию, которая отрисовывает прямоугольник с заданными размерами (a, b) на изображении размера (m, n), цвет фона задайте в схеме RGB, как и цвет прямоугольника. Цвета также должны быть параметрами функции. Напишите аналогичную функцию но для овала с полуосями a и b. Напишите тесты для кода.
Примечание: уравнение эллипса (границы овала) можно записать как:
<h1>$\frac{(x-x_0)^2}{a^2}+\frac{(y-y_0)^2}{b^2}=1$

In [1]:
def draw_rectangle(a, b, m, n, rectangle_color, background_color):
    # Your code goes here
    pass

def draw_ellipse(a, b, m, n, ellipse_color, background_color):
    # Your code goes here
    pass

<h1>Задача 7. Дан некий временной ряд. Для данного ряда нужно найти его: математическое ожидание, дисперсию, СКО, найти все локальные максимумы и минимумы (локальный максимум - это точка, которая больше своих соседних точек, а локальный минимум - это точка, которая меньше своих соседей), а также вычислить для данного ряда другой ряд, получаемый методом скользящего среднего с размером окна $p$.
<h1>Примечание: метод скользящего среднего подразумевает нахождение среднего из подмножетсва ряда размером $p$

In [ ]:
# Your code goes here

<h1> Задача 8. Дан некоторый вектор с целочисленными метками классов, напишите функцию, которая выполняет one-hot-encoding для данного вектора
<h1> One-hot-encoding - представление, в котором на месте метки некоторого класса стоит 1, в остальных позициях стоит 0. Например для вектора [0, 2, 3, 0] one-hot-encoding выглядит как: [[1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0]]